# Generated by Django 5.2.3 on 2025-07-13 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_cartitem_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='image_path',
            new_name='image',
        ),
    ]
