# Generated by Django 5.2.3 on 2025-07-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_tour_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ImageField(null=True, upload_to='tour_images/'),
        ),
    ]
