# Generated by Django 5.2.4 on 2025-07-15 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='available',
        ),
    ]
