# Generated by Django 5.2.3 on 2025-07-15 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='available',
        ),
    ]
