# Generated by Django 5.2.4 on 2025-07-18 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_alter_cart_user_alter_review_tour'),
        ('tours', '0009_remove_orderitem_items_orderitem_order'),
    ]

    operations = [
    ]
