# Generated by Django 5.2.4 on 2025-07-24 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0011_tour_buyers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='buyers',
        ),
        migrations.AlterField(
            model_name='tour',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tickets_amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='BoughtTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.tour')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bought_tours', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
