# Generated by Django 5.2.4 on 2025-07-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0012_remove_tour_buyers_alter_tour_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boughttour',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
