# Generated by Django 5.2.4 on 2025-08-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0014_remove_orderitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boughttour',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
