# Generated by Django 5.2.4 on 2025-08-05 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0016_boughttour_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 5, 15, 39, 57, 109429, tzinfo=datetime.timezone.utc)),
        ),
    ]
