# Generated by Django 5.2.4 on 2025-08-07 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0017_cartitem_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 7, 15, 41, 36, 972348, tzinfo=datetime.timezone.utc)),
        ),
    ]
