# Generated by Django 5.2.4 on 2025-07-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_avatar_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='/avatars/default-avatar-icon-of-social-media-user-vector.jpg', null=True, upload_to='avatars/'),
        ),
    ]
