# Generated by Django 5.2.4 on 2025-07-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Processing'), (3, 'Shipped'), (4, 'Completed'), (5, 'Canceled')], default=1),
        ),
    ]
