services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    restart: on-failure

  web:
    build: .
    command: >
      sh -c "python manage.py migrate --noinput &&
            uvicorn zentour.asgi:application --host 0.0.0.0 --port 8080"

    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app:rw
    restart: on-failure

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy

  test:
    build: .
    command: >
      sh -c "python manage.py migrate --noinput &&
            pytest"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app:rw
    restart: "no" 

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A zentour beat --loglevel=info
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0

  celery-beat:
    build: .
    command: celery -A zentour beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - redis
      - web
  
  celery-worker:
    build: .
    command: celery -A zentour worker --loglevel=info
    depends_on:
      - redis
      - web
    environment:
      - DJANGO_SETTINGS_MODULE=zentour.settings


volumes:
  db_data: